settings: fix settings force closes in monkey test squashed
commit ba94c7cae4bb34f65f8e51a2ecfe7c9de0d747a4
Author: Jian Zhou <jianzhou@codeaurora.org>
Date:   Tue Sep 6 18:45:40 2016 +0800

    Settings: Fix settings force close in monkey test.

    UnrestrictedDataAccess null pointer causes settings force close in monkey
    test.

    Add null pointer protect.

    CRs-Fixed: 1057528

    Change-Id: I6a98c92e3f28639db7985d7c7331be0465c81f76
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 0fb609e736b731564306b935a514e2c9e029965a
Author: yumeng <yumeng@codeaurora.org>
Date:   Fri Sep 2 16:19:34 2016 +0800

    Settings: Occurred "com.android.settings" force close 15 times at
    java.lang.IllegalArgumentException: cannot apply policy to UID
    1001000 at monkey test mode.

    add pretection for monkey test mode.

    Change-Id: Ib6a76d44b8f46e2f4cfc1bf57ece0438c5bcdb5b
    CRs-Fixed: 1051409
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 172af8aa57cddce5197173421fdefc01bce90327
Author: Jian Zhou <jianzhou@codeaurora.org>
Date:   Wed Dec 14 02:42:30 2016 -0800

settings: fix settings force closes in monkey test squash1

    commit 6111c8f3bc632fa7fc9aedb710ef05b02bc89b0b
    Author: Zhaolei <zxin@codeaurora.org>
    Date:   Fri Sep 30 11:25:27 2016 +0800

        Settings:  Fix settings force close in monkey test.

        Unable to find explicit activity class {com.android.cellbroadcastreceiver/com.android.cellbroadcastreceiver.CellBroadcastSettings

        Check whether activity exists befor start activity.

        Change-Id: Ic69a1c51cd2aeea8fcb064a01241718a8cfe36df
        CRs-Fixed: 1069255
        Signed-off-by: mydongistiny <jaysonedson@gmail.com>

    commit 88689e6b04bcb4b91ff63b7294aa13c98a002b06
    Author: guangl <guangl@codeaurora.org>
    Date:   Thu Sep 22 19:35:23 2016 +0800

        Settings: Fix settings force close in monkey test.

        No Activity found to handle Intent
        {act=android.intent.action.MANAGE_PERMISSIONS}

        Check whether activity exists befor start activity.

        Change-Id: Ie373d760cbd22a3b24b4b735b3a5fbe290fc25c4
        CRs-Fixed: 1069238
        Signed-off-by: mydongistiny <jaysonedson@gmail.com>

    commit a9f840baeecdb472d974a85fc0fc9c9dd17bb80c
    Author: guangl <guangl@codeaurora.org>
    Date:   Thu Sep 22 15:52:07 2016 +0800

        Settings: Fix settings force close in monkey test.

        accessPreference.mState null pointer causes settings force close in
        monkey test.

        Add null pointer protect.

        Change-Id: Ia866ac02c8d75308d3ff99f1400f11318f898621
        CRs-Fixed: 1069229
        Signed-off-by: mydongistiny <jaysonedson@gmail.com>

    commit 2eced2159323d2210996733f8bb1efeb85b48508
    Author: guangl <guangl@codeaurora.org>
    Date:   Thu Sep 22 11:51:45 2016 +0800

        Settings: Fix settings force close in monkey test.

        userDictionaryPreference null pointer causes settings force close in
        monkey test.

        Add null pointer protect.

        Change-Id: I4a8cce4a2e228bc405e896cd77fc9c3756ca265d
        CRs-Fixed: 1069216
        Signed-off-by: mydongistiny <jaysonedson@gmail.com>

    commit e649a0082a96aae3927ad4667e2be3b9219abce1
    Author: Jian Zhou <jianzhou@codeaurora.org>
    Date:   Tue Sep 27 17:35:01 2016 +0800

        Settings: Fix AssertionError in monkey

        AssertionError will throws during in monkey, add a try catch to
        protect this.

        Change-Id: Ibdf89c869b4a30305855e2179de070915aab6aac
        CRs-Fixed: 1069294
        Signed-off-by: mydongistiny <jaysonedson@gmail.com>

    commit 73a7f5c5d68ad7c1f6c5b07fc6544fbfa2fad985
    Author: Jian Zhou <jianzhou@codeaurora.org>
    Date:   Tue Sep 27 16:29:16 2016 +0800

        Settings: Fix SparseArray null pointer issue in monkey issues

        SparseArray null pointer causes monkey test exception, add a
        protect for this.

        Change-Id: Iade3148a846962875f5f38c5d2bf5631d0d9ac42
        CRs-Fixed: 1069288
        Signed-off-by: mydongistiny <jaysonedson@gmail.com>

    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

Signed-off-by: mydongistiny <jaysonedson@gmail.com>